function generate_ppmtb_par(params)

params.input_file = strrep(params.input_file,'\','\\');
params.output_file = strrep(params.output_file,'\','\\');
params.transf_table = strrep(params.transf_table,'\','\\');


text = ['START OF PARAMETERS:\n',...
params.transf_table,'                      -file with transformation data\n',...
params.input_file,'                     -file with data to back-transform\n',...
num2str(params.n_vars),' ',num2str(params.columns),'                         - nvar, column numbers\n',...
'-9.0 1.0e21       - trimming limits\n',...
num2str(params.cellsx ),' ',num2str(params.cellsy), ' 1 1                   - nx, ny, nz, nreal (ignored if nx = 0)\n',...
params.output_file,'                    -file for back transformed values\n',...
'0                              -enforce N(0,1)? (0=no,1=yes)\n'];


fid = fopen(params.ppmtb_par_file,'wt');
fprintf(fid, text);
fclose(fid);
end

